source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'rails-api'
gem 'sqlite3'

group :development do
  gem 'spring'
end

group :development, :test do
  gem 'byebug'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'pry'
end

group :test do
  gem 'database_cleaner'
  gem 'faker'
  gem 'shoulda'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
